### PR TITLE
Add support for configuring language mode via vim 'filetype' setting

### PR DESCRIPTION
**Pull request by dbarnett**
Allows using the vim `:set` command to query and override the language mode:
```vim
:set filetype?
:set ft?
:set filetype=clike
:set filetype=
```

### CODE REVIEW

**Comment by dbarnett** [comment]
Caveat: Changing the mode doesn't seem to totally work. I tried setting to clike in the vim demo and it had some coloring and indentation behavior that was not quite clike. But that could be fixed in setOption, which already tries to handle 'mode' specially, and even just the querying is something I've been wanting for a while.

Some parts like the alias handling could be generalized. Could do that as follow-up or on the second setting that needs it.

**Comment by dbarnett** [comment]
Oh, the mode quirks might have been specific to how 'clike' is configured on the demo/vim.html page. I tried hacking some other pages and it seemed to work fine.

**Comment by mightyguava** [comment]
I'd rather `set` didn't special case `filetype`. It opens up the path for a lot of clutter in `set`. Can you use the new callback support in ddbf33f and use `defineOption` to build this behavior instead? Aliasing `ft` to `filetype` in `set` is fine to me though.

**Comment by dbarnett** [comment]
Awesome, agree that will be much better. One thing, though: What's the best way to get access to the `cm` object from this callback?

**Comment by mightyguava** [comment]
Ah I didn't think that far. The options API here doesn't actually support local options. I've expanded it in https://github.com/codemirror/CodeMirror/pull/3200. Please take a look and see if it fits your requirements

**Comment by dbarnett** [comment]
Updated to use option callbacks and refactored alias registration. PTAL.

I did change the arg order of `Vim.defineOption` to add `aliases` before `callback` and keep the callback last. Shouldn't affect any callers since the callback arg was just added, but I could just as easily make it a separate `Vim.defineOptionAlias` func or whatever makes sense to you.

**Comment by mightyguava** [comment]
Thanks. Merged as 346d16c and added 2c45249

**Comment by dbarnett** [comment]
> Caveat: Changing the mode doesn't seem to totally work. I tried setting to clike in the vim demo and it had some coloring and indentation behavior that was not quite clike.

I figured out what was going on with the clike mode quirks here. You have to set the mode to "text/x-csrc" instead of "clike" for it to load the right options. So `setOption('mode', getOption('mode'))` loses information, which is unfortunate.

**Comment by marijnh** [comment]
@dbarnett At the CodeMirror level, doing `instance.setOption("mode", instance.getOption("mode"))` should not lose any information (the original value is preserved at the mode option's value). Is that what you were talking about?

**Comment by dbarnett** [comment]
Aha, I had a small discrepancy getting the 'mode' option in a different way than I was setting it. Fix in #3218.

**Pull request closed without merging**
