### PR TITLE
Fix errors being thrown if an event emission results in a listener being synchronously removed

### PR DESCRIPTION
**Pull request by connor4312**
It would result in the array length changing and (from experience!) result a hard-to-track-down error.

### CODE REVIEW

**Comment by connor4312** [comment]
I apologize for introducing the dreaded scourge, the Semicolon, into this pristine codebase. I have exorcised it, lint should now pass.

**Comment by MattJustMatt** [comment]
@marijnh apologize for the tag/pressure here, although this PR is a blocker for us. Would love to get a review when you get a moment!

**Comment by marijnh** [comment]
Event handler arrays are not mutated anymore since d7b1370ca45d74 (5.21.0), so I am not sure what is going wrong here. Can you submit a test case that fails?

**Comment by connor4312** [comment]
I may have been on 5.20.x still, I'll check when I get into the office

**Comment by marijnh** [comment]
Can I close this?

**Comment by connor4312** [comment]
Yep, sorry for not getting back to you. This appears to be fixed in recent versions of CodeMirror.

**Pull request closed without merging**
