### PR TITLE
Add gap language mode support

### PR DESCRIPTION
**Pull request by mcmartins**
Simple mode GAP language support - http://gap-system.org/.

### CODE REVIEW

**Comment by mcmartins** [comment]
Did I forget to add something for the lint mode to pass the tests?

**Comment by marijnh** [comment]
Hi. I'm not currently accepting new modes. The recommended way to distribute a new mode is by putting it into a separate repository, and distributing it through npm under a name like `codemirror-gap-mode`.

**Comment by mcmartins** [comment]
Cheers, will be doing it. 

Are you keep track of these new mode modules? Or just following that naming convention will allow someone to find new modes easily? Or you keep a list updated in this repo?

Thanks!

**Comment by marijnh** [comment]
I'm not tracking these, at the moment, but we could add a list of externally maintained modes on the wiki, and link to that from `mode/index.html` in the repository/website. Does that sound workable?

**Comment by mcmartins** [comment]
I guess that would work. I'll let you know when everything is sorted out for this mode.

Cheers.

**Pull request closed without merging**
