### PR TITLE
first commit

### PR DESCRIPTION
**Pull request by idleberg**

### CODE REVIEW

**Comment by marijnh** [comment]
I'd like the filenames to match the theme names whenever possible. Would you prefer to add the `-dark` prefix to the filenames, or to remove it from the css classes?

**Comment by idleberg** [comment]
Oh, right. That's a remainder from base16-builder, removed it from the file classes!

**Comment by marijnh** [comment]
Your commit only modifies hopscotch.css. Should the same be done for the other files?

**Comment by idleberg** [comment]
👍

**Comment by marijnh** [comment]
All right. Merged as bc008c070f

**Pull request closed without merging**
