### PR TITLE
Produce macSublime & pcSublime keymaps from sublime.js

### PR DESCRIPTION
**Pull request by mtaran-google**
This will make it easier to get programmatic access to the content of these keymaps, per #5020

### CODE REVIEW

**Comment by mtaran-google** [comment]
erm, looks like the line 484/460 should be dealing with delLineRight, not smartBackspace

**Comment by marijnh** [comment]
Can you amend the patch?

**Comment by mtaran-google** [comment]
I can create a new one (I normally never deal with git). I suspected it would be cleaner if you wanted to fix this one, but I don't have a preference.

**Comment by marijnh** [comment]
You can update a branch that has a pull request, the new commits will appear in the pull request.

**Comment by marijnh** [comment]
Thanks. Merged as 1951460e52e2e

**Pull request closed without merging**
