### PR TITLE
filter out duplicate messages 2

### PR DESCRIPTION
**Pull request by erosman**
ref: #6490
#6491 failed due The keyword 'const' is reserved (174:6) !!??
Changed to var

### CODE REVIEW

**Comment by bruchmann** [comment]
You don't need to open a new pull request. Just `git push` to the old one.

**Comment by erosman** [comment]
I don't develop on Github so I don't know about `git push` :(

**Comment by marijnh** [comment]
Addons need to run as-is on IE9, so that indeed means no `const`. But the `includes` method is also not available there, so you'd have to `indexOf` instead and compare the result to `-1`.

Updating the branch that the PR refers to updates the PR, so indeed, there's not need to open new ones to add or change patches.

**Comment by erosman** [comment]
Thanks @marijnh for the explanation. Updated the code to use `indexOf`

**Comment by marijnh** [comment]
Thanks. Merged!

**Comment by erosman** [comment]
@marijnh I was thinking, is arrow function supported or should it be changed to normal function?

e.g.
```js
anns = anns.filter(item => message.indexOf(item.message) > -1 ? false : message.push(item.message));
```

Should it be changed to?
```js
anns = anns.filter(function(item) {return message.indexOf(item.message) > -1 ? false : message.push(item.message);});
```

**Comment by marijnh** [comment]
Yes, it should. I've done so in 4f37b1e9

**Pull request merged**
