### PR TITLE
[vim] Correct the scroll position for zt & zb.

### PR DESCRIPTION
**Pull request by alur**
zt was placing 40% of the line above the visible area, and zb was placing it too high.

### CODE REVIEW

**Comment by marijnh** [comment]
@mightyguava @heppe Want to take a look at this?

**Comment by alur** [comment]
Added a couple of tests.

**Comment by heppe** [comment]
one minor style nit, but other than that, this looks good to merge.

**Comment by alur** [comment]
Fixed the whitespace in the tests.

**Comment by heppe** [comment]
looks good to merge

**Comment by marijnh** [comment]
Thanks! Merged as 237a6b6

**Pull request closed without merging**
