### PR TITLE
A Mathematica mode for CodeMirror

### PR DESCRIPTION
**Pull request by cbarbat**
This is a mode for the Mathematica syntax.
Mathematica is copyright by Wolfram Research Inc.

### CODE REVIEW

**Comment by marijnh** [comment]
Thanks. Are you sure it is worth including a list of a thousand character names (weighting over a 100kb), rather than just matching anything that looks like `\[foo]` as a character reference?

**Comment by marijnh** [comment]
Actually, the same goes for the ridiculously long list of keywords. This would be, if merged, by far the biggest mode file in the distribution. Since a lot of people are going to be downloading the file without ever using it, I don't think that's okay. If you can't cut down the list of keywords/builtins to something more reasonable, this is probably best hosted in a separate repository.

**Comment by cbarbat** [comment]
@marijnh I managed to reduce the size of mathematica.js to about 5.5 kbytes.

**Comment by marijnh** [comment]
Wonderful! Merged as de9a6b9

**Pull request closed without merging**
