### PR TITLE
Remove moot `version` property from bower.json

### PR DESCRIPTION
**Pull request by kkirsche**
Per bower/bower.json-spec@a325da3

### CODE REVIEW

**Comment by marijnh** [comment]
Please see #2569 and reach some kind of consensus with @laurelnaiad

**Comment by kkirsche** [comment]
Na. But consider that Bower may be under NPM anyway which is still something being discussed bower/bower#1520

**Comment by kkirsche** [comment]
Also their maintainer says they probably won't ever use it: http://stackoverflow.com/questions/24844901/bowers-bower-json-file-version-property

**Comment by marijnh** [comment]
All right. Attached patch removes it along with the line in the release script that was responsible for updating it.

**Pull request closed without merging**
