### PR TITLE
Fixing hotkeys for addCursorTo(Prev|Next)Line

### PR DESCRIPTION
**Pull request by tbertelsen**
#5109 This change fixes issue #5109. See details in issue thread.

### CODE REVIEW

**Comment by marijnh** [comment]
Looks like you forgot to adjust some tests.

@mtaran and @dwelle does the approach taken here look okay to you?

**Comment by dwelle** [comment]
LGTM for PC, as for mac no idea...

In my sublime text 2 default OSX keymap, there's:

```
	{ "keys": ["ctrl+shift+up"], "command": "select_lines", "args": {"forward": false} },
	{ "keys": ["ctrl+shift+down"], "command": "select_lines", "args": {"forward": true} },
```

which seems to be current behavior in CM..

**Comment by mtaran-google** [comment]
Looks good to me.

**Comment by adrianheine** [comment]
@tbertelsen If you squash your commits I will merge them :)

**Comment by marijnh** [comment]
I've done the squashing, and merged this as 40570ddc

**Pull request closed without merging**
