### PR TITLE
Optimizing BranchChunk.insertInner for large files

### PR DESCRIPTION
**Pull request by 2is10**
Fixes issue #4021 by avoiding repeated splicing of large arrays.

### CODE REVIEW

**Comment by marijnh** [comment]
Thanks for looking into that! Merged as 5cf02c9187a8, and updated in 9ad383797c28 to simplify, remove comparison with `undefined` (which worked, but is a little too obscure), and fix the way the new chunks are inserted into the parent `children` array (using `push` only works when the content is inserted into the last child, which is always the case when loading content, but not when, for example, pasting a big chunk in the middle of a file).

**Comment by 2is10** [comment]
Thanks for promptly evaluating and accepting the patch, and for the fix and improvements.

My company’s a prelaunch startup without a revenue stream yet, but I’ll see if I can get you a recurring contribution of some size. We appreciate all of your fantastic work on CodeMirror.

**Comment by marijnh** [comment]
Woah, I somehow missed the second part of this patch (the spilling of branch chunks) when reviewing, and that turned out to be broken, corrupting documents when gradually grown above ~500 lines. Reverted that part in 0d4374d10ee32b

**Comment by 2is10** [comment]
Yikes! I thought the new code was functionally equivalent. My patch touched both functions b/c the first calls the second, and both were doing repeated splicing of large arrays. I’m sorry for the trouble.

**Comment by marijnh** [comment]
Yeah, the splicing is less large-scale in the second, but it would probably still benefit from being optimized. We'll just have to figure out where the bug is.

**Pull request closed without merging**
