### PR TITLE
Add sml

### PR DESCRIPTION
**Pull request by yeguanghao**

### CODE REVIEW

**Comment by marijnh** [comment]
It doesn't look like mllike.js defines that mime type. Did you forget to add a file to the commit?

**Comment by cprieto** [comment]
I had been refactoring the ML mode (for both F# and OCaml), I can take care and add SML to the ML like languages (and define x-sml as a type).

What do you reckon @marijnh ?

**Comment by marijnh** [comment]
Yes, adding a definition for plain ML sounds like a good idea.

**Comment by marijnh** [comment]
This has been addressed by #5173

**Pull request closed without merging**
