### PR TITLE
Allow comments between async and function keywords

### LINKED ISSUE #5078: `async` keyword is not highlighted if followed by a comment
```js
async /* comment */  function hello(x) {
  console.log(x);
}
```

The `async` doesn't get highlighted if there is a comment between it and `function`

### PR DESCRIPTION
**Pull request by JoelEinbinder**
fixes #5078

### CODE REVIEW

**Comment by marijnh** [comment]
Oh, oops, I just committed something very similar in 85fb7510.

**Comment by JoelEinbinder** [comment]
Mine has a test :)

**Comment by marijnh** [comment]
Test merged as 1ba861a0

**Comment by JoelEinbinder** [comment]
Yay

**Pull request closed without merging**
