### PR TITLE
Fix indentation after a var with the $

### PR DESCRIPTION
**Pull request by dmitrykiselyov**
For example:
```stylus
v1 = $v2
  |new line

body
  color $c
    |new line
```

### CODE REVIEW

**Comment by dmitrykiselyov** [comment]
I hope this pull request will be :sparkles: :pray:

**Comment by dmitrykiselyov** [comment]
What the best way to do a pull request with only the latest commit in the master branch of my forked repository?  I was guided by [this](http://stackoverflow.com/questions/5561161/how-to-do-a-pull-request-in-github-with-only-the-latest-commit-in-the-master-bra).

**Comment by marijnh** [comment]
Merged as a726389. This pull request is fine -- it only contains the relevant commit. The trick is not to start from some diverging local branch, but to create a branch that is exactly the same as my master branch, and then create your commit(s) on top of that. `git rebase` can be useful for this.

**Comment by dmitrykiselyov** [comment]
Thanks :+1:  Next time I will try `git rebase`.

**Pull request closed without merging**
