### PR TITLE
'dialog-opened' class when dialog is triggered

### PR DESCRIPTION
**Pull request by goldsmcb**
Thanks for considering my other PR about adding insertBefore to the dialog. I think this approach is less invasive to the existing dom structure and allows for styling like this to avoid the dialog covering up the first few lines of text in the editor.
```
.dialog-opened .CodeMirror-scroll {
	margin-top: 40px;
}
```

An advantage I see with this is it gives the application an indication of when a dialog is opened, allowing for many styling opportunities.

### CODE REVIEW

**Comment by marijnh** [comment]
This is a good idea. However, CodeMirror is targeting pre-`classList` browsers so you'd have to formulate it using the `CodeMirror.addClass` and `CodeMirror.rmClass` utilities instead.

**Comment by goldsmcb** [comment]
Nice I didn't know about the addClass and rmClass utilities, hows this new commit looking?

**Comment by marijnh** [comment]
Much better, thanks!

**Comment by goldsmcb** [comment]
Awesome! Any chance you could tell me when the next release would be?

**Comment by marijnh** [comment]
Next week. Release monthly around the 20th.

**Comment by jdbruxelles** [comment]
@goldsmcb [here](https://codemirror.net/doc/releases.html) is all release notes and version history.

**Pull request merged**
