### PR TITLE
Groovy mode enhancements

### PR DESCRIPTION
**Pull request by glaforge**
* added the new "trait" keyword
* added support for the dollar slashy string $/foo/$
* support the string interpolation in all the string variants that support string interpolation

### CODE REVIEW

**Comment by marijnh** [comment]
I'm closing this until further activity.

**Comment by glaforge** [comment]
Fair enough. I haven't had time at all to further work on this :-(
When I find a moment to come back on this topic, should I create a new issue, and reference it from here?

**Comment by marijnh** [comment]
Either way is fine.

**Comment by glaforge** [comment]
ok thanks (and sorry again for lack of time)

**Pull request closed without merging**
