### PR TITLE
XQuery: Keyword lists updated (support for XQ31, XQFT, XQUP)

### PR DESCRIPTION
**Pull request by ChristianGruen**
Thanks for this nice and efficient library!

We are using CodeMirror in the Database Administration UI of BaseX. I have updated the keywords lists by adding all keywords of the most recent W3 XQuery 3.1, XQuery Full Text and XQuery Update recommendations, and I have removed some few obsolete/non-standard keywords.

### CODE REVIEW

**Comment by marijnh** [comment]
Thanks. Merged as c49bb5fed2a and followed up with 22861a03a517 (it'd be nice if you could run the tests or address failing continuous integration next time).

**Comment by ChristianGruen** [comment]
Thanks for both merging the code and hinting me to the CI tests.

**Comment by marijnh** [comment]
Oh, there's another test failing. You seem to have remove `private` as a keyword. Is that intentional?

**Comment by marijnh** [comment]
Also `this`, `throws`, `finally`, and `null`

**Comment by ChristianGruen** [comment]
There are actually no such keywords in XQuery. In XQuery 3.1, annotations (`%private`, `%public`, `%updating`), but I think these are not considered so far in the highlighter.

**Comment by marijnh** [comment]
Adjusted the tests in 404d869

**Pull request closed without merging**
