### PR TITLE
Add missing standard CSS property names / values (per MDN)

### PR DESCRIPTION
**Pull request by orionlee**
Added a set of standard CSS properties and correspond value keywords, based on [MDN](https://github.com/mdn/browser-compat-data).

Included is a utility that can be used to identify missing property names / values by comparing the config in `css.js` against MDN.

<details>
  <summary>Propertiies added (reached CR)</summary>

Property names:
```
  "mask-clip",
  "mask-composite",
  "mask-image",
  "mask-mode",
  "mask-origin",
  "mask-position",
  "mask-repeat",
  "mask-size",
  "mask-type",
  "paint-order",
  "touch-action"
```

Correspond property value keywords:

```
{
  "mask-image": [
    "multiple_mask_images",
    "svg_masks"
  ],
  "mask-origin": [
    "fill-box",
    "stroke-box",
    "view-box"
  ],
  "touch-action": [
			"axis-pan",
			"manipulation",
			"pinch-zoom",
			"unidirectional-pan"
  ]
}
```
</details>

### CODE REVIEW

**Comment by orionlee** [comment]
By using the utility, the followings can possibly be added too.

<details>
  <summary>Non standard properties, that is in working draft state</summary>

```
[
  "-webkit-line-clamp",
  "aspect-ratio",
  "border-end-end-radius",
  "border-end-start-radius",
  "border-start-end-radius",
  "border-start-start-radius",
  "color-adjust",
  "counter-set",
  "initial-letter-align",
  "initial-letter",
  "inline-size",
  "margin-trim",
  "overflow-anchor",
  "overflow-block",
  "overflow-inline",
  "overscroll-behavior-block",
  "overscroll-behavior-inline",
  "overscroll-behavior-x",
  "overscroll-behavior-y",
  "overscroll-behavior",
  "scrollbar-color",
  "scrollbar-width",
  "text-decoration-thickness",
  "text-underline-offset",
  "transform-box"
]
```
</details>

<details>
  <summary>Misc. property values that are missing</summary>

(The list include a few that are not keywords that need to be filtered out, e.g. `2_value_syntax`.)

```
{
  "align-content": [
    "flex_context",
    "grid_context"
  ],
  "align-items": [
    "flex_context",
    "grid_context"
  ],
  "align-self": [
    "flex_context",
    "grid_context"
  ],
  "all": [
    "revert"
  ],
  "animation-direction": [
    "alternate-reverse"
  ],
  "animation-timing-function": [
    "jump"
  ],
  "appearance": [
    "compat-auto"
  ],
  "background": [
    "SVG_image_as_background",
    "background-clip",
    "background-origin",
    "background-size",
    "multiple_backgrounds"
  ],
  "background-attachment": [
    "multiple_backgrounds"
  ],
  "background-image": [
    "gradients",
    "image-rect",
    "image-set",
    "multiple_backgrounds",
    "svg_images"
  ],
  "background-position": [
    "multiple_backgrounds",
    "4_value_syntax"
  ],
  "background-position-x": [
    "two_value_syntax"
  ],
  "background-position-y": [
    "2_value_syntax"
  ],
  "background-repeat": [
    "multiple_backgrounds",
    "round_space",
    "2-value"
  ],
  "background-size": [
    "contain_and_cover"
  ],
  "block-size": [
    "fit-content",
    "max-content",
    "min-content"
  ],
  "border-bottom-left-radius": [
    "elliptical_corners",
    "percentages"
  ],
  "border-bottom-right-radius": [
    "elliptical_corners",
    "percentages"
  ],
  "border-image": [
    "gradient",
    "optional_border_image_slice"
  ],
  "border-radius": [
    "elliptical_borders",
    "percentages",
    "4_values_for_4_corners"
  ],
  "border-top-left-radius": [
    "elliptical_corners",
    "percentages"
  ],
  "border-top-right-radius": [
    "elliptical_corners",
    "percentages"
  ],
  "box-shadow": [
    "multiple_shadows",
    "spread_radius"
  ],
  "break-after": [
    "multicol_context",
    "paged_context",
    "region_context"
  ],
  "break-before": [
    "multicol_context",
    "paged_context",
    "region_context"
  ],
  "break-inside": [
    "multicol_context",
    "paged_context",
    "region_context"
  ],
  "caption-side": [
    "writing-mode_relative_values"
  ],
  "clear": [
    "flow_relative_values"
  ],
  "column-fill": [
    "balance-all"
  ],
  "column-gap": [
    "flex_context",
    "grid_context",
    "multicol_context"
  ],
  "column-width": [
    "intrinsic_sizes"
  ],
  "content": [
    "alt_text",
    "element_replacement"
  ],
  "cursor": [
    "bidirectional_resize",
    "grab",
    "unidirectional_resize",
    "url_positioning_syntax",
    "zoom"
  ],
  "display": [
    "display-outside",
    "flow-root",
    "multi-keyword_values",
    "ruby_values",
    "table_values"
  ],
  "flex-basis": [
    "max-content",
    "min-content"
  ],
  "float": [
    "flow_relative_values"
  ],
  "font": [
    "font_stretch_support",
    "system_fonts"
  ],
  "font-family": [
    "system_ui"
  ],
  "font-size": [
    "rem_values",
    "xxx-large"
  ],
  "font-stretch": [
    "percentage"
  ],
  "font-style": [
    "oblique-angle"
  ],
  "font-variant": [
    "css_fonts_shorthand",
    "greek_accented_characters",
    "turkic_is",
    "uppercase_eszett"
  ],
  "font-variant-alternates": [
    "annotation",
    "character_variant",
    "ornaments",
    "styleset",
    "stylistic",
    "swash"
  ],
  "font-weight": [
    "number"
  ],
  "gap": [
    "flex_context",
    "grid_context",
    "multicol_context"
  ],
  "grid-template-columns": [
    "animation",
    "fit-content",
    "minmax",
    "subgrid"
  ],
  "grid-template-rows": [
    "animation",
    "fit-content",
    "minmax",
    "subgrid"
  ],
  "height": [
    "fit-content",
    "max-content",
    "min-content"
  ],
  "hyphens": [
    "afrikaans",
    "bosnian",
    "bulgarian",
    "catalan",
    "croatian",
    "czech",
    "danish",
    "dutch",
    "english",
    "esperanto",
    "estonian",
    "finish",
    "french",
    "galician",
    "german_reformed_orthography",
    "german_swiss_orthography",
    "german_traditional_orthography",
    "hungarian",
    "icelandic",
    "interlingua",
    "italian",
    "kurmanji",
    "latin",
    "lithuanian",
    "norwegian_nn",
    "norwegian_no",
    "polish",
    "portuguese",
    "portuguese_brazillian",
    "russian",
    "slovenian",
    "spanish",
    "swedish",
    "turkish",
    "ukrainian",
    "upper_sorbian",
    "welsh"
  ],
  "image-rendering": [
    "crisp-edges",
    "pixelated"
  ],
  "justify-content": [
    "flex_context",
    "grid_context"
  ],
  "justify-items": [
    "flex_context",
    "grid_context"
  ],
  "justify-self": [
    "flex_context",
    "grid_context"
  ],
  "letter-spacing": [
    "svg"
  ],
  "list-style-type": [
    "ethiopic-halehame",
    "ethiopic-halehame-am",
    "string"
  ],
  "max-block-size": [
    "fit-content",
    "max-content",
    "min-content"
  ],
  "max-height": [
    "fit-content",
    "max-content",
    "min-content"
  ],
  "max-inline-size": [
    "fit-content",
    "max-content",
    "min-content"
  ],
  "max-width": [
    "fit-content",
    "max-content",
    "min-content"
  ],
  "min-block-size": [
    "fit-content",
    "max-content",
    "min-content"
  ],
  "min-height": [
    "fit-content",
    "max-content",
    "min-content"
  ],
  "min-inline-size": [
    "fit-content",
    "max-content",
    "min-content"
  ],
  "min-width": [
    "fit-content",
    "max-content",
    "min-content"
  ],
  "mix-blend-mode": [
    "svg"
  ],
  "offset-path": [
    "path-support",
    "ray-support"
  ],
  "opacity": [
    "percentages"
  ],
  "overflow": [
    "multiple_keywords"
  ],
  "overflow-wrap": [
    "anywhere"
  ],
  "place-content": [
    "flex_context",
    "grid_context"
  ],
  "place-items": [
    "flex_context",
    "grid_context"
  ],
  "place-self": [
    "flex_context",
    "grid_context"
  ],
  "position": [
    "absolutely_positioned_flex_children",
    "position_sticky_table_elements",
    "sticky"
  ],
  "quotes": [
    "quotes_auto"
  ],
  "resize": [
    "block_level_support",
    "flow_relative_support"
  ],
  "rotate": [
    "x_y_z_angle"
  ],
  "row-gap": [
    "flex_context",
    "grid_context"
  ],
  "ruby-position": [
    "inter-character"
  ],
  "shape-image-threshold": [
    "percentages"
  ],
  "shape-outside": [
    "gradient",
    "image"
  ],
  "tab-size": [
    "length"
  ],
  "text-align": [
    "flow_relative_values_start_and_end",
    "justify-all",
    "match-parent",
    "string"
  ],
  "text-combine-upright": [
    "digits"
  ],
  "text-decoration": [
    "shorthand"
  ],
  "text-decoration-style": [
    "wavy"
  ],
  "text-emphasis-position": [
    "left_and_right"
  ],
  "text-indent": [
    "each-line",
    "hanging"
  ],
  "text-orientation": [
    "sideways"
  ],
  "text-overflow": [
    "fade_function",
    "fade_value",
    "string",
    "two_value_syntax"
  ],
  "text-size-adjust": [
    "percentages"
  ],
  "text-transform": [
    "dutch_ij_digraph",
    "full-size-kana",
    "full-width",
    "greek_accented_characters",
    "lowercase_sigma",
    "turkic_is",
    "uppercase_eszett"
  ],
  "text-underline-position": [
    "from-font",
    "left_right",
    "under"
  ],
  "transform": [
    "3d"
  ],
  "transform-origin": [
    "support_in_svg"
  ],
  "transition": [
    "gradients"
  ],
  "transition-property": [
    "IDENT_value"
  ],
  "transition-timing-function": [
    "jump"
  ],
  "unicode-bidi": [
    "isolate",
    "isolate-override",
    "plaintext"
  ],
  "white-space": [
    "break-spaces",
    "svg_support",
    "textarea_support"
  ],
  "width": [
    "animatable",
    "fit-content",
    "max-content",
    "min-content"
  ],
  "word-spacing": [
    "percentages",
    "svg"
  ],
  "writing-mode": [
    "horizontal_vertical_values",
    "sideways_values",
    "svg_values"
  ],
  "z-index": [
    "negative_values"
  ],
  "clip-path": [
    "animations",
    "basic_shape",
    "fill_and_stroke_box",
    "html",
    "path",
    "svg"
  ],
  "filter": [
    "svg"
  ],
  "pointer-events": [
    "html_elements"
  ]
}
```
</details>

**Comment by marijnh** [comment]
Thanks! I don't want the script in the repository, but I've merged the added words as a2e86b621151 and 1ac4e320224eb006

**Comment by orionlee** [comment]
I'm just curious for the reasons of excluding the script: I feel they could be useful for future updates. Maybe not wanting to add new dependency (or changes) to CodeMirror 5?

**Comment by marijnh** [comment]
My experience is that these kinds of scripts tend to bitrot in a forgotten corner of the repository. Putting it somewhere in a gist and linking it from here (or keeping the branch alive) might be useful, but I don't want to load down the repository with too much auxiliary code.

**Comment by orionlee** [comment]
Ah, I could understand the sentiment. Anyway, I intend to leave the branch there so if you want to use it in the future it's there.

I considered further automating it, but realized anything further would probably need to be discussed and done separately from this PR.

**Pull request closed without merging**
