### PR TITLE
situations, when type should not be parsed as a keyword

### PR DESCRIPTION
**Pull request by zaggino**
```
class HasType {
  type: string;
  constructor(type: string) {
    this.type = type;
  }
  setType({ type }: { type: string; }) {
    this.type = type;
  }
}
```
tested this as a valid typescript code

### CODE REVIEW

**Comment by adrianheine** [comment]
This also works with `string`, `any`, `number`, … Microsoft's monaco editor also highlights them as keyword.

**Comment by zaggino** [comment]
@marijnh I've added code to make the test-case pass. Can you please have a look at this?
All JavaScript and TypeScript tests are passing for me. Thanks!

**Comment by marijnh** [comment]
I've merged your tests as 00f59d1a50ec and pushed 486507818, which solves the problem in a different way by only making `type` a keyword when at the start of a statement.

**Comment by zaggino** [comment]
Thanks!

**Pull request closed without merging**
