### PR TITLE
[tern demo] Use protocol relative URLs

### PR DESCRIPTION
**Pull request by aviraldg**
https://codemirror.net/demo/tern.html is broken at the moment; this fixes it

### CODE REVIEW

**Comment by marijnh** [comment]
How does this fix anything? `ternjs.net` doesn't support HTTPS, so it'll just break things in a different way.

**Comment by aviraldg** [comment]
That's something only you can fix :sweat_smile:

**Comment by marijnh** [comment]
Yes, I'll put it on my list (though messing around with SSL certs isn't my favorite hobby)

**Comment by idleberg** [comment]
@aviraldg Protocol-relative URLs are now an [anti-pattern](http://www.paulirish.com/2010/the-protocol-relative-url/)

**Pull request closed without merging**
