### PR TITLE
Added SVG to modeInfo

### PR DESCRIPTION
**Pull request by teolag**
SVG files should be handled as xml files

### CODE REVIEW

**Comment by marijnh** [comment]
Mime types ending in `+xml` are automatically treated as XML, so this isn't necessary.

**Comment by teolag** [comment]
Yes I know that, but the functions findModeByExtension and findModeByFileName returns null with a filename ending with .svg
Or am I doing something wrong?

**Comment by marijnh** [comment]
That's a good point. Attached patch adds `svg` as a file extension, and makes `findModeByMIME` handle fallback for `+xml` and `+json` MIMEs.

**Comment by teolag** [comment]
Thank you for seeng my problem!
Your commit looks great! Happy new year!

**Pull request closed without merging**
