### PR TITLE
Jumptoline addon and added yo search demo.

### PR DESCRIPTION
**Pull request by mihailik**
See [#3030 for previous discussion](https://github.com/codemirror/CodeMirror/issues/3030#issuecomment-161665462)

This adds jumpToLine.js addon and jumpToLine command bound to Alt-G as @marijnh suggested.

The accepted inputs are:

* `linenumber` (one-based)
* `:linenumber` same as above, to match habitual format for 'go to line' in Chrome DevTools
* `+linenumber` and `-linenumber` for line relative to current
* `line:column`
* `%scroll` for position on scrollbar (proportional to line count, not character count neither pixel height)
* `+scroll%` and `-scroll%` for position on scrollbar relative to current

In case when character offset/column is not specified, we jump to line preserving offset/column as possible.

### CODE REVIEW

**Comment by mihailik** [comment]
@dpursehouse @davido

Does this look OK?

**Comment by marijnh** [comment]
Looks good to me. I've merged it as f1519ad5057 , and cleaned it up a little in 291b06eb8. The only externally visible change I made is that I renamed the file to `jump-to-line.js` to conform to the way other addons files are named.

**Comment by dpursehouse** [comment]
Nice.  Any idea when this will be in a release?

**Comment by marijnh** [comment]
I do releases around the 20th of each month, so in two weeks 5.10 will be coming out.

**Comment by davido** [comment]
Nice job indeed. Really appreciated.

**Comment by dpursehouse** [comment]
Then we can get it into Gerrit 2.13. I don't think we can wait 2 weeks to
release 2.12.

**Comment by davido** [comment]
Ack.

**Comment by mihailik** [comment]
Thanks a lot @marijnh ! I've spotted a couple of things:

1. zero-based character offsets — this is the most important, as majority of editors and tools use one-based line/columns, so copy-pasting positions will be ever so slightly off
2. remnants of search.js addon docs in the comment/header
3. semicolons — are you intentionally migrating to no-semicolon rule? it's a bit jarring when only a couple of lines skip them and others stick to old-style semicolon

Look at #3683 *Cleanup of the header, consistency tweaks* for fixes to (2) and (3).

I wasn't sure if (1) is intentional, so didn't fix it yet. But please consider it, as it might make CodeMirror feel buggy if it always lands you one-character off what you expect.

**Comment by marijnh** [comment]
> zero-based character offsets

For what it's worth, Emacs uses zero-based column offsets as well, which I feel makes sense (before the first character is position zero, after the first character position 1), and which has actually never caused problems with copy-pasted positions from other tools for me -- gcc, babel, and everything else I routinely use spits out zero-based columns.

Since zero-based is what CodeMirror uses, I don't think it is a good idea to make this addon so something different.

> are you intentionally migrating to no-semicolon rule?

Yes. I don't think it makes sense to update existing code yet, though there'll be a big move to ES6 modules and ES6 code in the future, at which point I'll remove all semicolons and start enforcing semicolon-free style.

Thanks for your PR!

**Pull request closed without merging**
