### PR TITLE
[vim] Fix vim-mode-change event signalled twice

### PR DESCRIPTION
**Pull request by benhormann**
Fix for #6296, and tests.

### CODE REVIEW

**Comment by benhormann** [comment]
I found a test that fails:
```
  test('v', 'visual');
  test(':', '');
  test('<Esc>', 'normal'); // failure: 'normal;normal' != 'normal'
```
However if you press those keys on vim.html, it just stays in visual mode.
_For reference, Vim goes to normal mode._

@marijnh What do you reckon?
IMO it's a separate issue, and very unlikely to affect anyone (asides from having to press <Esc> twice).

**Comment by marijnh** [comment]
As long as that isn't a regression caused by this PR, I'm okay with merging as-is.

**Comment by benhormann** [comment]
Not a regression. I'm sure because this keymap doesn't listen to its own events.

**Comment by marijnh** [comment]
Thanks!

**Pull request merged**
