### PR TITLE
moved colorforth to theme folder; minor fix to demo page

### PR DESCRIPTION
**Pull request by drom**

### CODE REVIEW

**Comment by drom** [comment]
There are some historical (cultural) reasons behind creating of this colorforth theme for Forth mode.
I hope to get some involvement form Forth community by doing so. Here is the blog about it: 
http://blogs.msdn.com/b/ashleyf/archive/2013/11/02/colorforth.aspx

**Comment by marijnh** [comment]
I am actually aware of colorforth (I did have a Forth phase a long time ago), but I don't believe that the lack of contrast in this theme are necessary for a colorforth look -- grey text on slightly darker grey background is a bad idea in any context. If you can (significantly) up the contrast, either by darkening the background or brightening the text (or even both), I'll be happy to merge this in.

**Comment by drom** [comment]
You are right, It is not very good contrast. I have tweaked some colors. Does it look better?

snapshot13

I would like to keep different background for compilation and interpretation time, so.

**Comment by marijnh** [comment]
Thanks. Merged as 41a740b19ba. Next time, please try to rebase your pull request branch, rather than leaving in merge commits, so that it is easier for me to pick out the relevant patches.

**Pull request closed without merging**
