### PR TITLE
Update Material Theme syntax to the official version

### PR DESCRIPTION
**Pull request by equinusocio**
This PR will update Material Theme syntax to match the official theme and add the new material theme variants.

### CODE REVIEW

**Comment by marijnh** [comment]
Could you undo the reformatting of all of demo/theme.html please?

@vincentwoo and @mkaminsky11, you've worked on the material theme before, how does this look to you?

**Comment by equinusocio** [comment]
@marijnh yep! I will do it now. 

Ps: i'm Mattia Astorino the author of material theme. You can check my profile :)

**Comment by marijnh** [comment]
Ah, I see, your name is even in the original file. Thanks for fixing the formatting!

**Comment by equinusocio** [comment]
@marijnh There are upcoming releases planned? Because i have another PR ready to add my other theme, [Moxer](https://github.com/moxer-theme/moxer-code)

**Comment by marijnh** [comment]
CodeMirror uses a monthly release cycle, with new releases happening around the 20th of each month.

**Comment by equinusocio** [comment]
Ok so next release will live next month?

**Comment by marijnh** [comment]
Yes (5.48.4 came out this Monday)

**Pull request merged**
