### PR TITLE
Support attributes in markText function

### PR DESCRIPTION
**Pull request by AlexanderPrendota**
Fix for: https://github.com/codemirror/CodeMirror/issues/5672
The same like in [`1a028d`](https://github.com/codemirror/CodeMirror/commit/1a028d007a50c117775aabca1e5d932115333e9f).

If all is file I'll add the description.

Thanks!

PS.
Tell me please How I can build and test this changes.

### CODE REVIEW

**Comment by marijnh** [comment]
I'd prefer a mechanism that allows any arbitrary attribute, at which point we can also use that to implement `title` and `css` under the covers, rather than adding more and more arguments to functions.

If you `npm install` the dependencies, you can run `npm build` to rebuild the library, and open `test/index.html` in a browser to run the tests.

**Comment by AlexanderPrendota** [comment]
@marijnh Hello! Support all attributes instead of `title`, `area-label` and etc

**Comment by marijnh** [comment]
You have a number of lint failures. Also, could you add support for the old `title` property on marks by creating a field in an attributes object when it is present?

**Comment by AlexanderPrendota** [comment]
=) legacy code.
I will but you can mark new release with BREAKING CHANGES notice

**Comment by marijnh** [comment]
> I will but you can mark new release with BREAKING CHANGES notice

That's what I'm trying to avoid, obviously. Does the patch break anything else?

**Comment by marijnh** [comment]
This'll also need an update to the docs, and some new tests. And then there's the question of how attributes that conflict with attributes that the editor itself sets (such as `class`) are handled. Do we disallow those? Or try to merge the values somehow?

**Comment by AlexanderPrendota** [comment]
shouldn't. I just added 

```js
attributes = {}
...
// support for the old title property
// https://github.com/codemirror/CodeMirror/pull/5673
if (m.title) {attributes.title = m.title}
``

**Comment by AlexanderPrendota** [comment]
We can disallow the `class` and `style` attributes. I think

**Comment by AlexanderPrendota** [comment]
For docs:
```
attributes: object
When given, will give the nodes created for this span a HTML attributes with the given value.
```

**Comment by marijnh** [comment]
You can edit `doc/manual.html` to update the docs (and you'll want to mention contracts like not allowing `style`/`class`).

**Comment by AlexanderPrendota** [comment]
@marijnh Please check

**Comment by marijnh** [comment]
The lint failures are still there (click the `Details` link in the travis check if you aren't running the tests locally).

**Comment by AlexanderPrendota** [comment]
Hm...I have no idea what's going wrong. How my patch can affects this tests? Could you take a look please?
screen shot 2018-11-19 at 5 01 02 pm

**Comment by marijnh** [comment]
Oh, sorry, no, those do fail on some browsers, but if you run `npm test` you'll get the same thing that runs on the continuous integration server, and shouldn't be seeing those.

**Comment by AlexanderPrendota** [comment]
Hm..I still have no idea 😔

```
> node ./test/run.js
mode/kotlin/kotlin.js: Trailing whitespace (106:7)
mode/kotlin/kotlin.js: The keyword 'let' is reserved (35:2)
src/line/line_data.js: Semicolon found (189:53)
src/line/line_data.js: Semicolon found (226:100)
src/line/line_data.js: Semicolon found (227:95)
src/line/line_data.js: Semicolon found (261:66)
src/line/line_data.js: Semicolon found (262:85)
src/line/line_data.js: Semicolon found (265:59)
src/line/line_data.js: Semicolon found (266:22)

All passed

npm ERR! Test failed.  See above for more details.
```

no details 😔

**Comment by AlexanderPrendota** [comment]
Please don't create a new version without this feature =)

**Comment by marijnh** [comment]
> Hm..I still have no idea

You pasted the exact error messages below that—you have to fix those lint errors to get the tests to pass.

Also, there still aren't any tests for this new feature.

**Comment by AlexanderPrendota** [comment]
please check

**Comment by marijnh** [comment]
Merged as ce1f0cd6f13d4 and corrected in 01758b195653844.

**Comment by AlexanderPrendota** [comment]
Awesome thanks!

**Pull request closed without merging**
