### PR TITLE
Small correction to Sublime keymap

### PR DESCRIPTION
**Pull request by kdekooter**

### CODE REVIEW

**Comment by marijnh** [comment]
On Linux, sort_lines is bound to F9/Ctrl-F9 by default. This may be a platform-dependent binding. What platform are you on?

**Comment by marijnh** [comment]
Looking at the default keymaps, yes, this is macOS-specific. Could you change your pull request to move the F9 bindings to `pcSublime` and put the F5 ones in `macSublime`?

**Comment by kdekooter** [comment]
Will do!

**Comment by marijnh** [comment]
Thanks!

**Pull request merged**
