### PR TITLE
Add `startingInner` property to multiplexing mode state.

### PR DESCRIPTION
**Pull request by AlbertHilb**
This PR intends to fix issue #5368

It adds `startingInner` property to multiplexing mode state.  That property is used, when `parseDelimiters` is true and `open` and `close` parameters are equal, to avoid the same substring starts and ends an inner mode.

Thanks

### CODE REVIEW

**Comment by AlbertHilb** [comment]
Is there any chance this will be merged or #5368 will be fixed in some other way?
I'll be glad if I can help you to make this happening.

**Comment by djbarker** [comment]
+1 on getting this fixed.

**Comment by marijnh** [comment]
Not sure what happened here, but I've pushed a slightly simpler patch  f015405 that should take care of this. Let me know if it doesn't work for you.

**Comment by djbarker** [comment]
Thanks.

**Pull request closed without merging**
