### PR TITLE
Update factor.js

### PR DESCRIPTION
**Pull request by kerabromsmu**
defineMode instead of defineSimpleMode - sort of simple mode simulation; slight optimization; fixed a few glitches.

### CODE REVIEW

**Comment by marijnh** [comment]
Woah, you basically reimplemented the simple mode addon. What limitation did you run into, precisely? And would it make sense to extend the simple mode addon instead?

**Comment by kerabromsmu** [comment]
Yep, you're right. I had to do it to make it work in adobe brackets. Turns
out they don't load the simple mode, and the way they let you load the
modules, I cannot use it. So I had to emulate it.

Actually, I made an extension for brackets that uses the same code and just
updated it here to match that one for consistency. Not only consistency,
but that too.

Not sure what you can do about it.

**Comment by marijnh** [comment]
Have you tried opening an issue for Brackets to load the simple-mode addon by default? It is tiny, and a bunch of modes are using it, so they may be open to that.

**Comment by kerabromsmu** [comment]
Actually, I don't remember. Probably I did, but still went for a quicker
solution, because otherwise I would have to wait for the next version of
brackets to release. I'll check anyway

**Comment by marijnh** [comment]
In any case, I'm not merging this, since it is simply duplicating code that's already in the distribution.

**Pull request closed without merging**
