### PR TITLE
Adding an option to disable auto indenting when auto closing tag based on slash

### PR DESCRIPTION
**Pull request by sobisht**
This PR is related to the issue #5129 

An option dontIndentOnAutoClose has been added which can be used to disable the code which indent the line when auto closing tags based on slash.
By default dontIndentOnAutoClose is false. This can be added as a property of "autoClosetags".

### CODE REVIEW

**Comment by marijnh** [comment]
The idea is good, but this should be implemented as an option to the _addon_, rather than the main editor. See, for example, the way `indentTags` is implemented in `closetag.js`.

**Comment by marijnh** [comment]
Much better, though you have some linter issues (trailing whitespace, a misaligned closing brace).

I notice `autoCloseGT` also indents lines in some circumstances. I guess the option should also disable that behavior.

**Comment by sobisht** [comment]
Thanks for suggestion. I have moved the option from src to addon. 
autoCloseGT is called when tags are auto closed based on opening tag (i.e. '>' in case of html tags). I have added this option specific to auto close based on slash.

**Comment by marijnh** [comment]
Right, but wouldn't it make more sense to have an option to control indentation in general, rather than one that only applies to the slash-key closing?

**Comment by sobisht** [comment]
Correct. Making the option general to auto close tags.

**Comment by marijnh** [comment]
Great! Merged as d9f05c90

**Pull request closed without merging**
