### PR TITLE
Refine image highlighting in markdown mode

### PR DESCRIPTION
**Pull request by HoverBaum**
According to the format suggested in #4082 add more information to images.

This implements formatting as suggested in the issue and adds tests for the implemented tokens. Also updates some tests with the new format.

With highlighting mode an image will now look like this:

```html
<span style="padding-right: 0.1px;">
    <span class="cm-formatting cm-formatting-image cm-image cm-image-marker">!</span>
    <span class="cm-formatting cm-formatting-image cm-image cm-image-alt-text">[</span>
    <span class="cm-image cm-image-alt-text">alt text</span>
    <span class="cm-formatting cm-formatting-image cm-image cm-image-alt-text">]</span>
    <span class="cm-formatting cm-formatting-link-string cm-string cm-url">(</span>
    <span class="cm-string cm-url">http://link.to/image.jpg</span>
    <span class="cm-formatting cm-formatting-link-string cm-string cm-url">)</span>
</span>
```

Giving a great deal of freedom to styling it however you like.

### CODE REVIEW

**Comment by marijnh** [comment]
Theme's don't come with an `image` style, so removing the `tag` styling will cause these to show up unstyled for everybody who isn't adding custom styling. That's not a good idea -- please preserve the `tag` styling.

**Comment by marijnh** [comment]
I'm okay with using the link tag, since there'll be additional classes to target for people who want to style these differently.

**Comment by HoverBaum** [comment]
Added `link` and adopted the tests accordingly.

**Comment by marijnh** [comment]
Looks great now! Merged as 34b3a7b

**Pull request closed without merging**
