### PR TITLE
Add preventCursorLeft/preventCursorRight options for atomic markers

### PR DESCRIPTION
**Pull request by thomasjm**
Per issue #5763. Hopefully it's this simple, seems to work for me. 

Would probably be good to add tests that the precedence works right when both options are provided. I'm having trouble running the tests locally though, `npm run test` produces errors like `ReferenceError: Can't find variable: addDoc (localhost:3000)`.

### CODE REVIEW

**Comment by marijnh** [comment]
Some of the errors in the travis run seem spurious (I can't see why they'd occur, and they don't occur for me locally), but the `core_atomicMarker` test is definitely failing for me (both in Firefox and Chrome).

Also, I prefer to avoid negatives in option names (because you get a double negative when you set them to false), and this applies not just to cursors but to any selection endpoints, so I'd prefer to rename these to `selectLeft` and `selectRight`, and inverse their meaning (making sure they now default to the inverse of the corresponding `inclusive` option).

Finally, you failed to update the anchor name in the docs for `preventCursorRight`.

**Comment by thomasjm** [comment]
Thanks for the review! I'll make those changes.

Can you give me a hint on how to run the tests? I've tried `npm install && npm run build && npm run test` and gotten the exact same failures as Travis (which doesn't include a `core_atomicMarker` failure). I also just tried rebasing on the latest master and got the same result.

**Comment by marijnh** [comment]
`npm test` is indeed how you run the tests, and they are passing on the master branch for me.

**Comment by thomasjm** [comment]
Sorry for the delay @marijnh -- I just took another look at this. Responded to your review, fixed up the tests and added specific tests for the fallback behavior. What do you think?

**Comment by marijnh** [comment]
Thanks! Merged.

**Pull request merged**
