### PR TITLE
Add "mustachelike"; "mustache", "handlebars" and vue.js use it

### LINKED ISSUE #3602: Support a Mustache mode that highlights the templated language
**Preface:** I'm opening this issue mostly for the technical discussion. If this feature seems possible and would be accepted into the project, I'd be happy to do the work.

I think that most often, Mustache template files have two extensions: the "wrapped" language extension, followed by ".mustache". So an HTML template file has the extension ".html.mustache" and a Markdown template might have the extension ".md.mustache".

It would be awesome if CodeMirror supported a mixed mode Mustache mode that highlighted the "wrapped" language as normal, and caught Mustache tags, highlighting them as Mustache tags.

One way that mustache makes this crazy simple is it's [crazy simple interface](https://mustache.github.io/mustache.5.html): Mustache tags are exactly the two following syntaxes: `{{tag}}` and `{{{tag}}}`. The mustache highlighter could distinguish between variables `{{name}}` and sections `{{#list}}`, etc., but honestly, if they were just plain text, that'd be fine.

The ["Set Delimiter"](https://mustache.github.io/mustache.5.html#Set-Delimiter) functionality would probably be hard to support, but I don't think it would be needed in v1. It's not a commonly used feature.

The only tricky thing I can think of is the Mustache mode knowing the file extensions, and dynamically using the proper mode for the "wrapped" language.

### PR DESCRIPTION
**Pull request by srawlins**
An alternative PR to #3611, fixes #3602, with @marijnh's suggestions.

* This creates a `mustachelike.js` which allows for easily writing new simple syntaxes that can be overlayed.
* Two modes are defined in the file: "mustache" and "handlebars".
* I chose "mustachelike" as [Mustache](https://en.wikipedia.org/wiki/Mustache_(template_system)) appears to be the father of [Handlebars](https://en.wikipedia.org/wiki/Handlebars_(template_system)).
* Django, Soy, and Tornado, are quite different from Mustache and Handlebars (they have `{% %}` syntax, for example, so that it wouldn't make sense to include them.

### CODE REVIEW

**Comment by marijnh** [comment]
Nope, still not really what I mean. So searching around the web, I have several websites telling me that Handlebars is a superset of Mustache syntax. So why, precisely, aren't you simply using the existing Handlebars mode and leaving it at that?

**Comment by srawlins** [comment]
Handlebars does appear to be essentially a superset of Mustache (Handlebars does not feature Mustache's [Set Delimiter syntax](https://mustache.github.io/mustache.5.html#Set-Delimiter), which my PR also does not include).

> So why, precisely, aren't you simply using the existing Handlebars mode and leaving it at that?

The handlebars mode does not support overlaying highlighting onto another language. Instead, every user who wants to overlay handlebars (or mustache) onto another language must copy and paste [7 lines](https://github.com/codemirror/CodeMirror/blob/master/mode/handlebars/index.html#L64..L70) and then make configurable per backdrop language. The goal was to have a mode that highlights Mustache syntax and accepts a backdrop language, the concept taken from vue.js.

**Comment by srawlins** [comment]
Should we instead apply the overlay configurability to the Handlebars syntax and be done with the Mustache parser?

**Comment by marijnh** [comment]
Patch 88a0257 does this. Give it a try.

**Comment by srawlins** [comment]
@marijnh Thanks much this is perfect! Thanks for your work!

**Comment by niftylettuce** [comment]
@marijnh @srawlins Can we please update documentation here <https://github.com/codemirror/CodeMirror/blob/master/demo/mustache.html>? 

```
mode: {name: "handlebars", base: "text/html"}
```

**Pull request closed without merging**
