### PR TITLE
Reduce setTimeout/clearTimeout calls from Delayed

### PR DESCRIPTION
**Pull request by alur**
This reduces the time the operation I mentioned in https://github.com/codemirror/CodeMirror/pull/5992 takes to ~450ms.

### CODE REVIEW

**Comment by marijnh** [comment]
This doesn't look like it's been tested—`onTimeout` is referred to without `this`, which seems like it should definitely break the code.

**Comment by alur** [comment]
Sorry about that. I originally wrote it in the compiled codemirror.js and thought I could rewrite it correctly in the source :)

**Comment by marijnh** [comment]
I had no idea setTimeout was _that_ expensive.

We still support IE8, so `Date.now` can't be used. Does this still perform as well using `+new Date`?

**Comment by tophf** [comment]
setTimeout is indeed very expensive, in Violentmonkey we've switched to using just one setTimeout call per event loop cycle in 99% of cases  instead of hundreds ([code](https://github.com/violentmonkey/violentmonkey/blob/master/src/common/cache.js)) so when the timer function runs it performs housekeeping on the entire cache and optionally reschedules itself to the closest expiry time.

**Comment by tophf** [comment]
>suspect using the performance tab in Chrome's devtools adds some extra overhead

Just to be sure you can measure the time without devtools by using console.time('foo') and console.timeEnd('foo'). 

<details><summary>Or run the low-overhead version of the devtools profiler</summary> 

chrome_2019-10-08_17-46-36

It also has a flamechart mode similar to the full profiler.
</details>

**Comment by alur** [comment]
Yeah, I took those measurements using console.time :)

**Pull request merged**
