### PR TITLE
[search addon] Make compatible with Trusted Types

### PR DESCRIPTION
**Pull request by vrana**
https://web.dev/trusted-types/ doesn't allow string innerHTML assignments. This change avoids it by using DOM instead.

### CODE REVIEW

**Comment by marijnh** [comment]
This looks good, in general, but would you be open to adding a feature to `el` where you can pass children as extra arguments, so that the code gets a bit less verbose? Something like

```
for (let i = 2; i < arguments.length; i++) {
  let child = arguments[i]
  element.appendChild(typeof child == "string" ? document.createTextNode(child) : child)
}
```

**Comment by vrana** [comment]
Done.

**Comment by marijnh** [comment]
Merged as 68d3399294abd37, updated in 336217837414a81 (there was an undefined reference to `dialogText` in the replace code)

**Comment by vrana** [comment]
Thanks.

**Pull request closed without merging**
