### PR TITLE
[manual] Minor fix to listed version number

### PR DESCRIPTION
**Pull request by vincentwoo**

### CODE REVIEW

**Comment by marijnh** [comment]
The manual reflects the exact current version number... this is intentional.

**Comment by vincentwoo** [comment]
Is this correct? Should it be 5.11.0, instead, then?

**Comment by marijnh** [comment]
The manual on the website reflects the current dev version, which I give its own patch version bump to distinguish it from published versions. There's a 5.11.0 manual in the zip file for 5.11.0.

**Comment by vincentwoo** [comment]
Ah, gotcha, thanks.

**Pull request closed without merging**
