### PR TITLE
set attribute [translate="no"]

### PR DESCRIPTION
**Pull request by aokiken**
I think don't need to translate programming code.

ref https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/translate

### CODE REVIEW

**Comment by marijnh** [comment]
It doesn't look like you've tested that code—you're calling `setAttribute` on a `Display` object, not a DOM element.

It would probably make more sense to set it on the input field anyway. Which would be implemented in `TextareaInput` (if translators translate textarea content at all) and `ContentEditableInput`.

**Comment by aokiken** [comment]
Thanks your feedback.

I'll check CONTRIBUTING.md.
https://github.com/codemirror/CodeMirror/blob/master/CONTRIBUTING.md

**Comment by aokiken** [comment]
I looking at https://github.com/codemirror/CodeMirror/commit/0b00c0e12fe919865929053e03b2c9dccda0779c Because I think this time changed seems to be similar to this.

**Comment by aokiken** [comment]
@marijnh 
> It doesn't look like you've tested that code—you're calling setAttribute on a Display object, not a DOM element.
Changed the target from Display to Display.wrapper

> Which would be implemented in TextareaInput (if translators translate textarea content at all) and ContentEditableInput.

I looking at 0b00c0e Because I think this time changed seems to be similar to this.

Programming code inside `[role="presentation"]` does not need to be translated.

**Pull request merged**
