### PR TITLE
package.json/dependency updates

### PR DESCRIPTION
**Pull request by brettz9**
- ~Enhancement: Add ES6 Module distributed file to build process; add minified files with terser and add source map files~
- ~Enhancement: For ESM bundlers, point to new distributed ESM entrance file as `module` in `package.json`~
- Refactoring: ~Switch from Buble to Babel 7 with preset-env (Buble was breaking on array destructuring) and~ update to latest Rollup API
- npm: Update node-static, Rollup deps; add npm-recommended `package-lock.json` ~and `package.json` linting recommended~ meta-data field[s]

Let me know if you need further clarification on any of these. Btw, I put the new ES distribution inside of `dist`. I could put it in `lib` also, but `dist` seemed more clear to me (though if it weren't backward-breaking, I'd think all of `lib` should be moved to `dist`). Let me know if you'd like it elsewhere.

### CODE REVIEW

**Comment by marijnh** [comment]
I'm not interested in switching to Babel. Please report the issue you ran into on the Bublé bug tracker and link it here—I'll take a look.

(Also, there's intentionally no package lock in the repository, so please don't add one.)

**Comment by brettz9** [comment]
I've rebased and reverted to Buble; I reported the issue with array destructuring at https://github.com/Rich-Harris/buble/issues/152

I also added `package-lock.json` to `.gitignore` to make clear your desire it not be added (though I personally find it helpful to know everyone is working against the same versions unless they wish to explicitly override).

Btw, are you open to a PR for ESLint and config that matches your current (intentional) conventions?

**Comment by marijnh** [comment]
Okay. But thinking about this a bit more, given that none of the modes or addons are loadable as ES modules, I actually don't think this is a very useful thing to provide.

No, i'm not interested in adding ESLint. I'm also not interested in getting random changes made to package.json (contributors are listed in the AUTHORS file, I'm really not sure why you'd go ahead and just add yourself to package.json when there's no other contributors listed there)..

**Comment by brettz9** [comment]
Ok, re: ESLint and re: `package.json`. I added `contributors` merely to get rid of the linting warnings I have for my `package.json` linter, and if I spent the time searching for who the others were, I would have wasted time because, as confirmed by your answer, I suspected you are pretty particular about how you want things, or rather, how you don't want things. Sometimes one makes a tentative PR and then without wasting a lot of time, get feedback to adjust accordingly; I would obviously add them if you had wanted the field.

As far as the modes/add-ons, would you be interested in my refactoring them as ES6 modules?

Until such time as dynamic import is available (so that one would merely need to pass the mode/add-on names to some CodeMirror method), one could perform static imports which may be imported and then passed the CodeMirror instance, e.g.,

```js
import CodeMirror from '...';
import cssMode from './modes/css/css.js';
cssMode(CodeMirror);
```

**Comment by marijnh** [comment]
> As far as the modes/add-ons, would you be interested in my refactoring them as ES6 modules?

No. Are you aware of the work around [CodeMirror 6](https://codemirror.net/6/)? That's going to be TypeScript and modules-from-the-ground up. I don't think it's worthwhile to make big, potentially disruptive changes to the way the existing version is distributed or maintained at this point. Tooling that integrates CommonJS modules into ES-module oriented bundlers works pretty well, in general.

**Comment by brettz9** [comment]
Okedoke, makes sense... I've amended the commit to minimize the scope... The one `package.json` meta-data field I thought should at least be kept was changing `maintainers` to `author` as it looks like that is how it is supposed to be expressed, with the [docs](https://docs.npmjs.com/files/package.json) merely mentioning that "npm also sets a top-level "maintainers" field with your npm user info."

**Comment by marijnh** [comment]
Right, now it just adds minified files... which is also something I didn't ask for (people tend to have their own build pipelines nowadays, and can do minification on that level). Sorry to be so resistant here, but opening a pull request that makes a number of unprompted changes is usually not a great idea—we have a way in which we've organized our project, and though that may not be the way you'd do it, we have our reasons.

So that just leaves the package.json tweaks and dependency upgrades, I guess. I'd happily merge those if you further reduce this.

**Comment by brettz9** [comment]
No worries... I had a cold today limiting what I could do anyways and just thought I'd do something light with the intent of using it down the road; but glad to hear full module support is apparently all part of the plan even if my help wasn't needed in this form.

I've amended to remove the minified files... Let me know if you would like me to remove the sourcemaps change as well for the non-minified `lib` file. Even for non-minified files, they can be useful for debugging (esp. development work that needs the option of looking back at the specific source files)...

**Comment by marijnh** [comment]
Nope, not a fan of source maps in distributed packages either (blows up the package size, users are only rarely interested in source locations)

**Comment by brettz9** [comment]
Ok, amended... That look all right?

**Comment by marijnh** [comment]
Yes. I'll wait for rollup to release my patch, and then merge this.

**Comment by adrianheine** [comment]
I've published bublé 0.19.4 with your patch.

**Comment by marijnh** [comment]
Great. Merged as 80eeba03634d . The rollup upgrade does seem to give us a bunch of cyclic dependency warnings, but I'm not immediately sure how to address those

**Comment by adrianheine** [comment]
I think that's my fault given that I implemented that warning in rollup and introduced the circular dependencies in CodeMirror :D

**Comment by marijnh** [comment]
Do I understand correctly that the Rollup warning is an approximation, and will fire even if the actual imports involved are not actually immediately accessed at load time (which I entirely understand—tracking what gets evaluated when is a whole different problem)?

**Comment by adrianheine** [comment]
Yeah, it just looks at the import graph, not at usage.

**Pull request closed without merging**
