### PR TITLE
[dust mode] Adds support for dust templates.

### PR DESCRIPTION
**Pull request by calmdev**
Dust was originally requested in #2353 and has been on the wish list for a few years.

http://www.dustjs.com/

### CODE REVIEW

**Comment by marijnh** [comment]
Hi. Thanks for contributing. However, we're aiming to move language modes into separate modules in the future, and are no longer accepting new languages in the core distribution. The recommended course of action is to publish and maintain this yourself, as a module called, say, `prosemirror-dust` on NPM.

**Comment by calmdev** [comment]
Do you have an example repo of how that should be done? It's not clear to me, because mode files have relative paths to other modes. If I was to place the mode into a standalone repo and require it those relative paths wouldn't resolve properly. I am seeing packages on NPM with new modes that appear to be entire forks of code mirror. Ideally the mode repos would only contain source files for the actual mode, right?

**Comment by claviska** [comment]
I second this. It's disenchanting to see a solid PR tossed out without a reasonable example of how it's expected to be contributed to the community. 😭

I appreciate the idea of moving to independent modes/themes, but I really think an example repo would provide a degree of consistency and help users integrate independent modes and themes easier.

Curious, will CodeMirror's core modes/themes be moved to independent repos at some point? That would provide more than enough of an example.

Thanks for the Dust contribution, @calmdev. And thanks for all your incredible work through the years, @marijnh. 👍

**Comment by almibe** [comment]
Do these help?
https://github.com/codemirror/CodeMirror/wiki/CodeMirror-addons
https://github.com/optick/codemirror-mode-elixir

**Comment by marijnh** [comment]
The [elixir mode](https://github.com/optick/codemirror-mode-elixir) is a good example. You specify the core module as well as other modes you depend on as dependencies, as you would with any NPM module.

As for it being disenchanting that I don't continue to adopt and maintain everybody's code, yeah, if that's what you've come to expect I've probably set the bar a bit too high in the past. I am, however, in no way obligated to keep expanding the amount of (largely unpaid) work I'm doing.

**Comment by calmdev** [comment]
Thanks guys. I'll work on setting up a repo and getting the mode published.

**Comment by calmdev** [comment]
https://github.com/nodewrite/codemirror-mode-dust
https://www.npmjs.com/package/codemirror-mode-dust

**Comment by marijnh** [comment]
Wonderful!

**Comment by adrianheine** [comment]
I added the mode to [the wiki page](https://github.com/codemirror/CodeMirror/wiki/CodeMirror-addons#external-modes).

**Pull request closed without merging**
