### PR TITLE
New addon: Tab list

### PR DESCRIPTION
**Pull request by WesCossick**
Tab list is a new addon in `/addon/edit/` that allows users to map the shift and shift-tab keys to these functions that will indent or unindent a Markdown list element.

### CODE REVIEW

**Comment by WesCossick** [comment]
@marijnh, thoughts on this PR?

**Comment by marijnh** [comment]
Hi Wes. This is too specific for including in the distribution. You'll have to keep it in your local code, or put it somewhere as an [external module](https://github.com/codemirror/CodeMirror/wiki/CodeMirror-addons).

**Comment by WesCossick** [comment]
Do you believe this addon is any more specifc than [continue list](https://github.com/codemirror/CodeMirror/blob/master/addon/edit/continuelist.js), which is already included in the repository? I would argue that each fulfils similarly useful and specific roles.

**Comment by marijnh** [comment]
Yes, it is, and also easier to implement locally. The list-continuing addon is also borderline too specific.

**Pull request closed without merging**
