### PR TITLE
Support Presto SQL

### PR DESCRIPTION
**Pull request by atavory**
This pull request adds support for [Presto SQL](https://prestodb.io/) syntax highlighting.

### CODE REVIEW

**Comment by marijnh** [comment]
Hi, we're not accepting new modes into the main distribution anymore. The recommended way to publish your mode is to put it in its own repository and publish it on npm---see for example the [elixir mode](https://www.npmjs.com/package/codemirror-mode-elixir).

**Comment by jdbruxelles** [comment]
Hi @marijnh,
You might put this message, "We're not accepting new modes..." in your website and in GitHub README.md 😉

**Comment by marijnh** [comment]
It is in CONTRIBUTING.md, which github points you to when you submit a new issue or pull request.

**Comment by atavory** [comment]
OK, thanks for the useful link, and sorry for missing this in the guidelines.

**Comment by codeStryke** [comment]
@atavory I want to use the presto mode with codemirror, and am curious to know if you published a package to npm?

**Pull request closed without merging**
