### PR TITLE
Change arrow appearance when a single line is collapsed

### PR DESCRIPTION
**Pull request by shw6rn**
This pull request addresses https://github.com/codemirror/CodeMirror/issues/4041

Add findMarksOnLine function which finds all marks on a line. Use findMarksOnLine in foldGutter.js to correctly find marks when a single line is collapsed.

### CODE REVIEW

**Comment by marijnh** [comment]
This pull request appears to just add a `findMarksOnLine` method (which is already well covered by `findMarks`), and doesn't do anything else. Did you forget a patch? (In any case, use `findMarks`, no need to add a new method.)

**Comment by marijnh** [comment]
... Oh, on closer look, the patch would have an effect, due to the changed meaning of the call in foldcode.js. I get what it does. Could you do it differently?

**Comment by shw6rn** [comment]
Yeah I could use `findMarks` instead

**Comment by shw6rn** [comment]
@marijnh I tried to use `findMarks` and there is an issue with that approach.
When you use `findMarks` to find all marks on line like so...
```
var line = cm.getLine(lineNumber);
var marks = cm.findMarks(CodeMirror.Pos(lineNumber, 0), Pos(lineNumber, line.length));
```
If the mark starts on the very end of the line, the fold mark is not returned from `findMarks` because the cursor position at the end of the line is the same `ch` position as the start of the mark (see https://github.com/codemirror/CodeMirror/blob/master/lib/codemirror.js#L7642)

We could resolve this issue in one of two ways.
1. Add the `findMarksOnLine` function as is
2. Change `findMarks` so that if the we are at the end of the line, use `span.from > to.ch` instead of `span.from >= to.ch` - this seems a little hacky and I'm not sure if this would have any adverse effects

**Comment by shw6rn** [comment]
Actually, `findMarks` looks like it will work if I go from from `Pos(lineNum, 0)` to `Pos(lineNum + 1, 0)`

**Comment by shw6rn** [comment]
@marijnh I made the fix using `findMarks` instead. Could you take a look?

**Comment by marijnh** [comment]
Thanks, looks good now. Merged as 431dd1b

**Pull request closed without merging**
