### PR TITLE
[stylus mode] New version

### PR DESCRIPTION
**Pull request by dmitrykiselyov**
Better auto-indent and highlighting.

### CODE REVIEW

**Comment by marijnh** [comment]
I've merged this as fc2def32c409 and 866934b3b1b4

Next time, please start from my version of the code, instead of simply continuing on your own old branch. That makes it easier for me to merge, and makes sure you actually get the code I merged. I've made a bunch of adjustments to code style, and made the linter pass. I'm not going to do that a 3rd time for this code.

**Comment by dmitrykiselyov** [comment]
Ok. Thanks for the adjustments to code style. How to run bin/lint?
I'll improve my knowledge of git and the next pull request will be shine :sparkles:

**Comment by marijnh** [comment]
You need to install node, then run `npm install` in the CodeMirror directory, and then `bin/lint` should run.

**Comment by dmitrykiselyov** [comment]
Thanks :+1: 
I think that with the $ sign (`$ bin/lint`) will be more obvious for Windows users :smile:

**Pull request closed without merging**
