### PR TITLE
[markdown] improve for HTMLs

### PR DESCRIPTION
**Pull request by laobubu**
## Commits

[markdown] support line-breaks in tags
[markdown] support multi-line blocks (eg. CDATA and comments)
[markdown] clear unused htmlState

## Example

```
<!-- Comments may contain

blank lines -->

<?php echo "good"; ?>

<![CDATA[ Support CDATA ]]>

<div id="xxx"
class="yyy">
    ↑ line-breaks are accepted between attributes
</div>
```

See:

- https://spec.commonmark.org/0.28/#example-146
- https://spec.commonmark.org/0.28/#example-147
- https://spec.commonmark.org/0.28/#example-149
- https://spec.commonmark.org/0.28/#example-614

## BTW, introducing ... [HyperMD](https://laobubu.net/HyperMD/)

**WYSIWYG Markdown editor** based on CodeMirror.
(Yes, it's *"What You See Is What You Get"*)

 [Demo](https://laobubu.net/HyperMD/)

### CODE REVIEW

**Comment by marijnh** [comment]
Could you add tests for this? I think we can avoid the `isInBlock` kludge by checking for `state.tagName || state.context` but without tests it's hard to be sure that I actually didn't break what you implemented.

**Comment by laobubu** [comment]
Tested. Both `tagName` and `context` are `null`.

**Comment by laobubu** [comment]
- [x] Added test cases
- [x] Fix: compatibility with `htmlmixed` mode *(previously only tested with `xml` mode)*

**Comment by marijnh** [comment]
Merged as 11dfc2f26 and followed up with 9ea789b9

**Pull request closed without merging**
