### PR TITLE
[mobile] disable autocomplete to ensure key event support

### PR DESCRIPTION
**Pull request by mtaran-google**
See https://code.google.com/p/chromium/issues/detail?id=118639#c209

You may have a better place to put this, or want to gate it on being Chrome, etc.

### CODE REVIEW

**Comment by marijnh** [comment]
Could you elaborate on the problem that is being solved by this? In principle, the editor should be able to handle compose events.

**Comment by mtaran-google** [comment]
I believe the original issue was that Chrome on Android would send the backspace key event but would not fill in the key code properly. It'd probably be easy to test it out when the next Android Chrome beta comes out, since I'm not sure if this will actually be an issue.

**Comment by marijnh** [comment]
Turning off autocomplete seems like a very indirect and complication-prone way to address this. So yeah, I'd prefer to test first and only go ahead if the problem persists.

**Comment by marijnh** [comment]
Closing this due to lack of response, feel free to comment/reopen if new information is available.

**Pull request closed without merging**
