### PR TITLE
Update gfm.js

### PR DESCRIPTION
**Pull request by ParthKolekar**
Remove SHA hash from being treated specially.

Now this will require 

// User/Project@SHA
// User@SHA

The existing regex matches arbitrary code that is a series of `[a-f0-9]{7,40}` not matter how they appear in a sentence.

### CODE REVIEW

**Comment by ParthKolekar** [comment]
Oh. Apparently github has this *issue* too where it marks anything with `[a-f0-9]{7,40}` as special.

**Comment by ParthKolekar** [comment]
Github uses CodeMirror. So it will obviously exhibit this behaviour. That was stupid.

**Comment by marijnh** [comment]
GitHub does allow linking of stand-alone hashes (as in 67379b827d111c97), so I don't think this is correct.

**Comment by ParthKolekar** [comment]
Agreed. This pull request is incorrect.

I didn't know about this feature that allows commit messages to become
valid links.

**Pull request closed without merging**
