### PR TITLE
Scheme mode fixes: properly marks 'atoms and '(lists of s-exp)

### PR DESCRIPTION
**Pull request by dsblank**
Also fixes `#;` comments

Fixes https://github.com/codemirror/CodeMirror/issues/5574

### CODE REVIEW

**Comment by marijnh** [comment]
Thanks! Could you make the indentation match the rest of the file (spaces, not tabs)? And maybe also add `()` to the set of characters that end a commented atom.

**Comment by dsblank** [comment]
Will do!

**Comment by dsblank** [comment]
By "commented atom", do you mean that you would like to properly handle:

```scheme
#; '(this is an sexp marked as an atom) but this is not
```

**Comment by marijnh** [comment]
No, I was thinking more in the direction of `(foo bar #;baz)`, but I've never used `#;` in the wild, so maybe it doesn't work the way I'm assuming it does (which is to comment out the expression after it)?

**Comment by dsblank** [comment]
Ah, I see. I think you are right. I'll see if I can fix this. (I have some other fixes, but I'll save those for another PR).

**Comment by dsblank** [comment]
Ok, it should address those issues.

**Comment by marijnh** [comment]
Thanks! Merged

**Pull request merged**
