### PR TITLE
support for ignoring whitespace within a line in diff

### PR DESCRIPTION
**Pull request by sfbayhacker**
This pull request includes changes to accommodate a new option - to ignore whitespace within a line. This does not ignore new line changes.

Requires user to pass option **ignoreWS** as true to ignore white space. Default is false.

### CODE REVIEW

**Comment by adrianheine** [comment]
I think I would prefer an option that takes a regular expression, but I don't know how @marijnh generally feels about this feature.

**Comment by sfbayhacker** [comment]
Appreciate your comment @adrianheine. Would you be able to point out the common use case(s) for a broader regular expression based approach? This is only to educate myself.

**Comment by marijnh** [comment]
I think the formulation is fine this way, since a regexp might match newlines, which would break the plugin. I merged this as 608e3f822d24 but followed up with a3891b51ec which makes the option name `ignoreWhitespace`, and simplifies the code a little.

**Comment by sfbayhacker** [comment]
Thanks @marijnh.

**Comment by sfbayhacker** [comment]
@adrianheine Ah, OK. Thanks. Appreciate you letting me know.

**Pull request closed without merging**
