### PR TITLE
Update .gitattributes

### PR DESCRIPTION
**Pull request by kunam1**

### CODE REVIEW

**Comment by kunam1** [comment]
Ibet

**Comment by kunam1** [comment]
Haha

**Comment by kunam1** [comment]
Hi app hay

**Comment by kunam1** [comment]
Hu

**Comment by kunam1** [comment]
Hu

**Comment by kunam1** [comment]
Lololo

**Comment by kunam1** [comment]
Hsjs

**Comment by kunam1** [comment]
Hsjs

**Comment by kunam1** [comment]
Ho

**Comment by kunam1** [comment]
Hahaha

**Comment by kunam1** [comment]
Hahaha

**Comment by kunam1** [comment]
Bababa

**Comment by jdbruxelles** [comment]
@kunam1 are you a bot ?

**Comment by marijnh** [comment]
No idea what this was. I banned the account since I can't really think of a valid justification for that kind of noise.

**Pull request closed without merging**
