### PR TITLE
Fixes wrong colors based on the official dracula theme

### PR DESCRIPTION
**Pull request by zenorocha**
Hello, 

I'm the creator of Dracula. First, I just wanted to say that it's super nice to see a Dracula theme over here. I'm a big fan of CodeMirror and I hope you guys keep doing this amazing work.

This pull request addresses some inconsistencies I noticed based on the [official color palette](https://github.com/dracula/dracula-theme/#color-palette).

### CODE REVIEW

**Comment by marijnh** [comment]
Thanks. Merged as 6709974

**Comment by zenorocha** [comment]
Thanks @marijnh!

**Comment by zenorocha** [comment]
Any idea when the next release will be?

**Comment by marijnh** [comment]
5.23 has been released

**Comment by zenorocha** [comment]
Awesome!

**Pull request closed without merging**
