### PR TITLE
Replace stream.match(/ +$/, false) with a more efficient regex

### PR DESCRIPTION
**Pull request by paddya**
With some inputs, especially when they contain long lines with many whitespace characters, `stream.match(/ +$/, false)` in the Markdown mode gets terribly slow. In our case, it could lock up the editor for 10s of seconds.

~~As a quick fix, I added a method `StringStream.matchTrailing(character)` which replicates the behavior of `StringStream.match()` for the special case of checking for specific trailing characters.~~

I changed the regex to `^ +$` which improves the performance a lot.

* All tests pass
* No complaints from `bin/lint`

### CODE REVIEW

**Comment by marijnh** [comment]
Does changing the expression to `stream.match(/^ +$/, false)` also yield the performance improvements that you're looking for?

**Comment by paddya** [comment]
@marijnh Yes! And it is so much simpler. I will change it.

**Comment by marijnh** [comment]
Thanks!

**Comment by paddya** [comment]
Thank you!

**Pull request merged**
