### PR TITLE
[julia mode] Julia 0.6 syntax updates

### PR DESCRIPTION
**Pull request by pabloferz**
This is an update to properly handle some syntax changes from Julia 0.6 (also includes some other fixes).

### CODE REVIEW

**Comment by pabloferz** [comment]
C.c. @marijnh

**Comment by marijnh** [comment]
Thanks, merged.

**Comment by danilaml** [comment]
@pabloferz Btw, is there a reason for `in` not to be included in keywords? (`for i in 1:42 ...`)

**Comment by pabloferz** [comment]
It is not included as a keyword but it is treated as an operator (in the example page over the codemirror site operators are not highlighted, but they are for example in jupyter notebooks).

**Comment by danilaml** [comment]
@pabloferz thanks for answering! Was confused since [here](https://docs.julialang.org/en/stable/manual/control-flow/#man-loops-1) it's referred as `the alternative (but fully equivalent) keyword in or ∈`

**Comment by jasonsun0310** [comment]
I think so, too. ''''struct''' is a recently added keyword to Julia to replace '''type'''. Perhaps code mirror didn't update this change in time.

**Pull request merged**
