### PR TITLE
ICEcoder's default theme

### PR DESCRIPTION
**Pull request by mattpass**
Spent quite a while perfecting this (IMO), but a lot of people seem to
really like it. Hope you do too.

Note: need to add to the themeing demo on the site, I didn't cover that.

### CODE REVIEW

**Comment by mattpass** [comment]
This is a sample of what the theme looks like BTW:

untitled-1

**Comment by vincentwoo** [comment]
Looks nice. Reminds me of a higher-contrast monokai

**Comment by mattpass** [comment]
Thanks. Was trying to use what I thought were the best parts of Seti, Monokai and Flatland.

**Comment by marijnh** [comment]
Merged as 8d79749. Have you considered making `variable-2` a little brighter? In JavaScript code, you'll often have a lot of these (http://codemirror.net/demo/theme.html#icecoder) and the current color makes for a rather low-contrast look.

**Comment by mattpass** [comment]
Good feedback, thanks. Looking at it, maybe is a bit subdued under JS mode. Put in a new pull request with a slight colour boost:

new-hex

**Pull request closed without merging**
