### PR TITLE
Prevent native search dialog from opening when persistent search dialog is open

### PR DESCRIPTION
**Pull request by 40thieves**
Prevents events for find commands when the persistent search dialog is open. This helps with accidental extra key presses.

### CODE REVIEW

**Comment by marijnh** [comment]
Would it make sense to also distinguish _which_ command the key refers to, and execute the appropriate action? It seems that for some of these commands, we could just execute the command itself, no?

**Comment by 40thieves** [comment]
Hmm, yes I can how that would be the better approach.

However I've just tested this out and there's a problem when calling the command for the first time. So for example: 

`find` command -> type "Hello" -> `findNext` command

Here, the search state has not been set to "Hello", and so the search is not run correctly. I suppose it could check if the search state is set and if not, trigger a `find` command.

**Comment by 40thieves** [comment]
I just realised I could call the callback instead of the `find` command - as this handles checking the search state

**Comment by 40thieves** [comment]
Updated to use the callback instead of custom logic. This doesn't necessarily solve the original problem, but it does clean up the original implementation.

**Comment by marijnh** [comment]
Any way we can at least make `findPrev` search backwards in this situation?

**Comment by 40thieves** [comment]
Updated again. Now `findNext` and `findPrev` commands will be executed (after setting the search state), whereas `find` and `findPersistent` will act as if enter was pressed.

I think this is a good heuristic...

**Comment by marijnh** [comment]
Thanks, that's what I was also thinking of. Merged as 5c6025a and adjusted a bit in b7b4269

**Comment by 40thieves** [comment]
Great! Thanks for the help in working out the implementation

**Pull request closed without merging**
